### ISSUE TITLE
Inclusion in node-red library

### ISSUE THREAD

**Issue by rafuz** [Spartan-II-117/node-red-contrib-home-assistant-llat#24]
Will this fork be included in node-red library?
This is the original repo --> [https://flows.nodered.org/node/node-red-contrib-home-assistant](url)

**Comment by Spartan-II-117** [comment]
I'll need to come up with a new name for it if so, but it is something I'm interested in pursuing.

**Comment by schford** [comment]
how about node-red-contrib-home-assistant-v2 

:-)

**Comment by FezVrasta** [comment]
Any news on this? It'd be great

**Comment by Spartan-II-117** [comment]
no news, but it is still a priority, life has just gotten crazy lately

**Comment by Spartan-II-117** [comment]
The new auth system gives the perfect opportunity, once we add support for Oauth, I will publish this project to NPM

**Comment by schford** [comment]
That will be great!

**Comment by flamingm0e** [comment]
Can you instead get permission from AYapejian to just take over his project and npm account?

I simply have too many flows and nodes to start over.  If I have to start over again, I don't know if it's worth it, and would likely forget node-red altogether for Home Assistant.  This is frustrating.

**Comment by simonszu** [comment]
@flamingm0e i'm not sure if you would have to start over completely at all. I think you will only need to export all your flows as a json, change the libraries, check if the node types have other names, if yes, search+replace them in your json, and re-import the json again.

**Comment by flamingm0e** [comment]
> @flamingm0e i'm not sure if you would have to start over completely at all. I think you will only need to export all your flows as a json, change the libraries, check if the node types have other names, if yes, search+replace them in your json, and re-import the json again.

That's a lot of work for me, using time I don't really have.

But again, what is the future of THIS fork? Is this fork going to be abandoned if the original developer comes back?  Am I going to have to do this all over again in a few months?  This is a situation in which a fork is good and bad, and there needs to be some cohesion between the 2.

**Comment by rafuz** [comment]
Having time there is no problem migrating from one fork to another one. Anyway for the future of the project it is useful to hear from the original author if he wants to expand the team to Spartan-II-117 and continue to develop it.
If AYapejian is sure to not come back than there is no point to continue to develop his project instead of going on with a new fork.

**Comment by aidbish** [comment]
I think spartan tried contacting the original owner without response, that's why he decided to for the project

**Comment by Spartan-II-117** [comment]
@flamingm0e my intention if the original dev comes back is to track his changes, so that noone using my fork has to revert to his. otherwise I'm aiming to make this transition as easy as possible, this will be a drop-in replacement for your existing nodes, with adding whatever i need to handle the new authentication system.

**Comment by Spartan-II-117** [comment]
The node is published as node-red-contrib-home-assistant-llat (for long lived-access token)

**Comment by rafuz** [comment]
What could be the better way to migrate existing nodes to the plugin?

**Comment by thomasvt1** [comment]
> What could be the better way to migrate existing nodes to the plugin?

What I did was;
* install node-red-contrib-home-assistant-llat
* Shutdown NodeRed
* Remove the old node-red-contrib-home-assistant folder
* Remove references in package.json and package-lock.json
* Start NodeRed
* You'll see an error that it's removing some config files
* Change password to token and done :)

**Comment by rafuz** [comment]
I am using the node-red hassio plugin from here [](https://github.com/hassio-addons/addon-node-red) and I am not sure on how to do that.
The modules directory is inside the package and I can't delete or uninstall the old node package in any way.

**Comment by simonszu** [comment]
Then you cannot. If there are any pre-shipped modules which aren't editable via the palette menu, you need to create an issue against the Plugin repository

**Comment by rafuz** [comment]
You are right, the node-red-contrib-home-assistant is pre-shipped into the plugin.
I will open an issue ad we will see what happens.
Thank you!
