### ISSUE TITLE
Does not support new home-assistant auth providers enabled by default in 77

### ISSUE THREAD

**Issue by Spartan-II-117** [Spartan-II-117/node-red-contrib-home-assistant-llat#32]
Node-red-contrib-home-assistant does not support the new auth system implemented by default in the new version of home assistant scheduled for release August 31st 2018

**Comment by schford** [comment]
No need to work around legacy currently enabled by default...(for anyone that is reading and is worried).

**Comment by Spartan-II-117** [comment]
@schford True, Thanks, that wasn't in place when i installed the beta

**Comment by Spartan-II-117** [comment]
The new release (published to NPM!) resolves this issue
